
spring:
  application:
    name: Smart Food Manager
  datasource:
    url: jdbc:mysql://localhost:3306/smart_food?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  web:
    locale: ja_JP
  messages:
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # snake_case のカラム名を camelCase に自動変換
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # コンソールにSQLログを表示
  mapper-locations: classpath:/mybatis/mapper/**/*.xml 

logging:
  level:
    root: WARN
    '[org.springframework.web]': DEBUG

server:
  port: 8080
  error:
    include-stacktrace: always

